[general]
import = [
  "./tokyo-night.toml"
] 
live_config_reload = true

[font]
normal = {family = "CaskaydiaCove Nerd Font Mono", style = "Regular"}
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
bold_italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
size = 18.0
