# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g @plugin "janoamaral/tokyo-night-tmux"

#Keybinds
bind-key C-f display-popup -E "tmux list-sessions -F '#S' | fzf | xargs tmux switch-client -t"

# initialize tmux plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
